before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/nivl/voorhees:{{ .Tag }}"
      - "ghcr.io/nivl/voorhees:v{{ .Major }}"
      - "ghcr.io/nivl/voorhees:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/nivl/voorhees:latest"
