name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  # https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/
  goreleaser:
    runs-on: ubuntu-latest
    env:
        DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Get Go version
        id: gover
        run: echo "::set-output name=value::^$(grep 'go 1.' go.mod | cut -d ' ' -f 2)"
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.gover.outputs.value }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
