name: Security
on: [push]
jobs:
  go-vulnerabilities-scan:
    name: "Golang Vulnerabilities Scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Generate go.list
        run: go list -json -m all > go.list
      - name: Run Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  gorelease-deprecation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unmaintained-deps-check:
    name: "Unmaintained deps check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Generate go.list
        run: go list -json -m all > go.list
      - name: Run Voorhees
        uses: Nivl/voorhees-github-action@ml/initial
